//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalificacionDocenteCursoEstudiante
    {
        public int CalificacionDocenteCursoEstudianteId { get; set; }
        public int CursoId { get; set; }
        public int EstudianteId { get; set; }
        public int PreguntasCalificacionCursoId { get; set; }
        public byte RespuestaPregunta { get; set; }
        public System.DateTime FechaEvaluacion { get; set; }
    
        public virtual Cursos Cursos { get; set; }
        public virtual Personas Personas { get; set; }
    }
}
