//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cursos
    {
        public int CursoId { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string TituloOtorgado { get; set; }
        public Nullable<int> ValorCurso { get; set; }
        public Nullable<int> DuracionHoras { get; set; }
        public Nullable<int> Docente { get; set; }
        public byte Estado { get; set; }
    
        public virtual Personas Personas { get; set; }
    }
}
