//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvidenciaCorreo
    {
        public int EvidenciaCorreoId { get; set; }
        public Nullable<byte> TipoCorrespondencia { get; set; }
        public string EmailDestino { get; set; }
        public string EmailRemitente { get; set; }
        public string Asunto { get; set; }
        public string Mensaje { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string EstadoEnvio { get; set; }
    }
}
