//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotasRapidas
    {
        public int NotaRapidaId { get; set; }
        public System.DateTime FechaPublicacion { get; set; }
        public System.DateTime FechaFinalizacion { get; set; }
        public string Titulo { get; set; }
        public string Mensaje { get; set; }
        public int UsuarioPublica { get; set; }
        public byte Estado { get; set; }
    
        public virtual Personas Personas { get; set; }
    }
}
