//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PanelInformativo
    {
        public int PanelInformativoId { get; set; }
        public byte[] Imagen { get; set; }
        public string ContetType { get; set; }
        public byte Estado { get; set; }
    }
}
