//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParticipacionEnForo
    {
        public int ParticipacionEnForoId { get; set; }
        public int ParticipanteId { get; set; }
        public int ForoTemaId { get; set; }
        public string Mensaje { get; set; }
        public System.DateTime FechaRegistro { get; set; }
    
        public virtual ForoTema ForoTema { get; set; }
        public virtual Personas Personas { get; set; }
    }
}
