//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personas
    {
        public int PersonaId { get; set; }
        public byte[] Imagen { get; set; }
        public string ContetType { get; set; }
        public string TipoDocumento { get; set; }
        public string NumDocumento { get; set; }
        public string NombreComplpeto { get; set; }
        public string CodigoInstitucional { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string Email { get; set; }
        public string Ciudad { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string Clave { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public byte Estado { get; set; }
    }
}
