//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SistemaCorreo
    {
        public int SistemaCorreoId { get; set; }
        public int RemitenteId { get; set; }
        public int DestinoId { get; set; }
        public string Asunto { get; set; }
        public string Mensaje { get; set; }
        public System.DateTime FechaEnvio { get; set; }
        public byte EstadoLectura { get; set; }
        public Nullable<System.DateTime> FechaLectura { get; set; }
    
        public virtual Personas Personas { get; set; }
        public virtual Personas Personas1 { get; set; }
    }
}
